<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Archana" failures="0" tests="1" name="userAPI.test.GetUserTests" time="1.166" errors="1" timestamp="2025-02-10T00:36:06 CST" skipped="0">
  <testcase classname="userAPI.test.GetUserTests" name="testGetUser" time="1.166">
    <error message="
[public void userAPI.test.GetUserTests.testGetUser(java.lang.String,java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testGetUser([java.lang.String arg0, java.lang.String arg1])
Arguments: [(java.lang.String) positive,(java.lang.String) all,(java.lang.String) 4.147671251E9,(java.lang.String) posi8323@gmail.com,(java.lang.String) A-166,(java.lang.String) Lincoln,(java.lang.String) Wisconsin,(java.lang.String) USA,(java.lang.String) 54252.0,(java.lang.String) https://userserviceapp-f5a54828541b.herokuapp.com,(java.lang.String) createusers,(java.lang.String) 201.0]" type="org.testng.internal.reflect.MethodMatcherException">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void userAPI.test.GetUserTests.testGetUser(java.lang.String,java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testGetUser([java.lang.String arg0, java.lang.String arg1])
Arguments: [(java.lang.String) positive,(java.lang.String) all,(java.lang.String) 4.147671251E9,(java.lang.String) posi8323@gmail.com,(java.lang.String) A-166,(java.lang.String) Lincoln,(java.lang.String) Wisconsin,(java.lang.String) USA,(java.lang.String) 54252.0,(java.lang.String) https://userserviceapp-f5a54828541b.herokuapp.com,(java.lang.String) createusers,(java.lang.String) 201.0]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:915)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- testGetUser -->
</testsuite> <!-- userAPI.test.GetUserTests -->
